# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2021-05-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accepterreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_bio', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bloodgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='donerreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('weight', models.IntegerField()),
                ('status', models.IntegerField()),
                ('bloodgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.bloodgroup')),
            ],
        ),
        migrations.CreateModel(
            name='donerstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateofdonation', models.DateField()),
                ('center', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user_role', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sendrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestdate', models.DateField()),
                ('accepterreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.accepterreg')),
                ('donerreg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.donerreg')),
            ],
        ),
        migrations.AddField(
            model_name='donerstatus',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.login'),
        ),
        migrations.AddField(
            model_name='donerreg',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.login'),
        ),
        migrations.AddField(
            model_name='accepterreg',
            name='bloodgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.bloodgroup'),
        ),
        migrations.AddField(
            model_name='accepterreg',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.login'),
        ),
    ]
